### ISSUE TITLE
[Feature request] Rotate tokens

### ISSUE THREAD

**Issue by krysztalzg** [Aedif/move-that-for-you#2]
Modules like Lasers & Lightbeams provide useful tools as actor tokens, can you make your module work with tokens?

**Comment by Aedif** [comment]
Had a go at it. Update to [1.4.0](https://github.com/Aedif/move-that-for-you/releases/tag/1.4.0) to check it out. Tell me if you find any issues.

**Comment by krysztalzg** [comment]
Thanks 🎉  I'll check it out sometime this week
